### PR TITLE
adapt constant expressions

### PR DESCRIPTION
**Pull request by xerc**
https://wiki.php.net/rfc/calls_in_constant_expressions

### CODE REVIEW

**Comment by aimeos** [comment]
Why is the backslash before PHP functions necessary?

**Comment by xerc** [comment]
for safety; "ensure that the function called is from the global namespace, even if there is a function by the same name in the current namespace" https://stackoverflow.com/questions/4790020/#answer-4790031

**Comment by xerc** [comment]
`(?<![\w\.\\>:])(abs|acosh|acos|array_chunk|array_column|array_count_values|array_diff_assoc|array_diff_key|array_diff|array_fill_keys|array_fill|array_flip|array_intersect_assoc|array_intersect_key|array_intersect|array_key_exists|array_key_first|array_key_last|array_keys|array_merge_recursive|array_merge|array_pad|array_product|array_replace_recursive|array_replace|array_reverse|array_search|array_slice|array_sum|array_unique|array_values|asinh|asin|atan2|atanh|atan|boolval|ceil|checkdate|chr|cosh|cos|count|decbin|dechex|decoct|deg2rad|doubleval|expm1|exp|floatval|floor|fmod|gettype|gmmktime|hash_algos|hypot|in_array|intdiv|intval|is_array|is_bool|is_countable|is_double|is_finite|is_float|is_infinite|is_integer|is_int|is_iterable|is_long|is_nan|is_null|is_numeric|is_object|is_real|is_resource|is_scalar|is_string|log10|log1p|log|max|min|pi|pow|rad2deg|range|round|sinh|sin|sizeof|sqrt|tanh|tan)(?=\s*\()`
=> `\\$1`

**Comment by aimeos** [comment]
This is not necessary because there are almost no functions in Aimeos and if yes, they are prefixed by `ai`.
In general, we are currently trying to simplify the code base as much as possible and avoid anything which is not really necessary.

**Comment by xerc** [comment]
ok ; than you should check for negations as in https://github.com/aimeos/aimeos-laravel/pull/447/commits/32c0c3e618b501a053350198a50475bc73a4dd67

**Pull request closed without merging**
