### PR TITLE
Jwt added , Omit Cookies

### PR DESCRIPTION
**Pull request by kappa-london**

### CODE REVIEW

**Comment by aimeos** [comment]
Thank you for your PR!

When looking into the implementation, this repository might be the wrong one because you need to add an authentication controller and some other stuff that must be part of the Laravel application. Thus, you should to implement or add these stuff in the Aimeos Laravel distribution instead: https://github.com/aimeos/aimeos

Furthermore, why do you create a mshop_basket table? I guess there's still a Laravel session where the Aimeos basket is stored in, isn't it?

**Comment by kappa-london** [comment]
Hi, thanks for the feedback. You're right we were a bit confused as well
because we had a call and we somewhat understood that changes would go for
this repo but later we figured out. We will have more attempts as we are
learning.

**Comment by aimeos** [comment]
@kappa-london Can you please move the RegisterController changes to the new https://github.com/aimeos/aimeos-headless distribution?

**Comment by aimeos** [comment]
Has been added to https://github.com/aimeos/aimeos-headless

**Pull request closed without merging**
