### PR TITLE
Bs4 upgrade pr

### LINKED ISSUE #218: Upgrade to Bootstrap v4.0.0 in the Admin UI
Hola Aimeos Folks,

first of all, i would let the let you know that we took a closer look since a few weeks to some modern shop applications, we decided to use aimeos to build a multisite shop prototype with automated deployment and complete automated rollout/setup scripts, now the prototype working super on multiple hostings and stages via git repo  👍 

We see your application as pretty forwarding, thank for your beautiful open source contribution including microdata following shema.org!!!

Here are the Questions:

- The frontend uses Bootstrap 3 which doesn't matter because it will be replaced completely, but there are planes to upgrade it to BS v4 ?

- The Admin uses BS4 alpha-6, do i am only using the wrong release or is the Admin UI not updated to BS4 stable release? Is upgrading planned or already done?

- How flexible I am in general with the frontend of the Admin UI? can i simply use vue or relpace BS 4 aplha-6 by my self?

Until now I have read only the README in this Repo and I am New to Laravel (coming from yii2)

### PR DESCRIPTION
**Pull request by dev7ch**
This update is quick teste on a local and live dev server, the console shows no errors and a basic worked as expected. Also i searched in the project for css classes and BR changes which are mentioned in the getbootstrap.com upgrade section.

Please review and test this PR, send me a PN if you would like to login in my live dev installation of the updated shop.

also tether.js is removed, is this ok? i guess it was used only for bootstrap?

fix #218

### CODE REVIEW

**Comment by aimeos** [comment]
Are there any errors/warnings in the browser console if you click through the admin interface?
The thether.js library was required by Bootstrap, maybe it's not any more if there's no warning in the console.

**Comment by dev7ch** [comment]
No after a 5 min check by clicking i havent seen errors in the console

**Comment by dev7ch** [comment]
btn, if i press "CMD + ALT + I" my chrome console doesnt show up, is this an important short cut for Aimeos?

**Comment by dev7ch** [comment]
ahh wait, there are some error with jquery 3.2.1 on the dash board

**Comment by dev7ch** [comment]
image
 except this all looks fine on a quick look ( not deeply tested)

**Comment by aimeos** [comment]
Seems like the JsonAdm REST API returns a 500 error. Was this the case before too?

**Comment by aimeos** [comment]
"CMD + ALT + I" is used for the supplier panel :-/

**Comment by dev7ch** [comment]
actually i dunno excatly, i dont have this error locally, only on dev live sever, i am running update now

**Comment by dev7ch** [comment]
Please could you have a look at your installation locally all works fine, this erro could be related to the delpoyer.php process:

you can simply install my pr brnach by:

- remove aiemos packages from composer.json
- run `composer update` (to delete vendor dependecies)
- run `composer require dev7ch/aimeos-laravel-bs4-test:dev-bs4-upgrade-pr`
- run `composer update`

**Pull request merged**
